const Constants = {
  TEST: 'TEST',
  TEST_CONNECTION: 'TEST_CONNECTION',
  CHANGE_VIEW_MODE: 'CHANGE_VIEW_MODE',
  SEARCH_HN: 'SEARCH_HN',
  SHOW_SEARCH_RESULTS: 'SHOW_SEARCH_RESULTS'
}
export default Constants;
