const Constants = {
  TEST: 'TEST',
  TEST_CONNECTION: 'TEST_CONNECTION',
  CHANGE_VIEW_MODE: 'CHANGE_VIEW_MODE',
  SEARCH_HN: 'SEARCH_HN',
  SHOW_SEARCH_RESULTS: 'SHOW_SEARCH_RESULTS',
  CREATE_NOTEBOOK: 'CREATE_NOTEBOOK',
  DELETE_NOTEBOOK: 'DELETE_NOTEBOOK',
  SHOW_NOTEBOOK: 'SHOW_NOTEBOOK',
  GET_NOTEBOOKS: 'GET_NOTEBOOKS',
  GET_NOTEBOOK: 'GET_NOTEBOOK',
  SHOW_NOTEBOOKS: 'SHOW_NOTEBOOKS',
  SAVE_RESULT_TO_NOTEBOOK: 'SAVE_RESULT_TO_NOTEBOOK'
}
export default Constants;
